# site settings
title: Flex Studio
subtitle: Ecommerce Specialists
email: ayo@flexstudio.io
description:  Build and optimize your e-commerce shop to boost conversion by up to 300%
subDescription:  Book a call to see how your conversion can be improved
# baseurl: # the subpath of your site, e.g. /blog
url: https://flexstudio.io/ # the base hostname & protocol for your site
author: Flex Studio
street_address: 37 Birch Drive
city: Parsons
state: KS
zip_code: 67357
country: United States of America
phone: (347) 687-8841

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/flexstudio.io
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
